[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "either"
allow = [
    "Apache-2.0",
    "MIT",
    "Unlicense",
]

[bans]
multiple-versions = "deny"
skip = [
    { name = "cfg-if", version = "0.1.10" },
    { name = "core-foundation", version = "0.7.0" },
    { name = "core-foundation-sys", version = "0.7.0" },
    { name = "core-graphics", version = "0.19.2" },
    { name = "hashbrown", version = "0.9.1" },
    { name = "dlib", version = "0.4.2" },
    { name = "libloading", version = "0.6.7" },
    { name = "nix", version = "0.18.0" },
    { name = "proc-macro-crate", version = "0.1.5" },
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
ignore = [
    "RUSTSEC-2021-0119"
]

[sources]
unknown-registry = "deny"
unknown-git = "allow"